urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^$', PostListView.as_view(),
        name='posts'),
    url(r'^tag/(?P<slug>[-\w]+)/$', TaggedPostListView.as_view(),
        name='tagged'),
    url(r'^new/$', login_required(PostCreateView.as_view(
        template_name='posts/post_form.html')),
        name='post_new'),
    url(r'^update/(?P<slug>[-\w]+)/$', login_required(PostUpdateView.as_view(
        template_name='posts/post_form.html')),
        name='post_update'),
    url(r'^delete/(?P<slug>[-\w]+)/$', login_required(PostDeleteView.as_view(
        template_name='posts/post_confirm_delete.html')),
        name='post_delete'),
    url(r'^profile/$', login_required(ProfileView.as_view(
        template_name='posts/profile.html')),
        name='profile'),
    url(r'^profile/update/$', login_required(profile_update),
        name='profile_update'),
    url(r'^profile/posts$', login_required(ProfilePostListView.as_view(
        template_name='posts/user_post_list.html')),
        name='my_posts'),
    url(r'^profile/comments$', login_required(ProfileCommentListView.as_view(
        template_name='posts/user_comment_list.html')),
        name='my_comments'),
    url(r'^users/(?P<pk>[\d]+)/$', UserDetailView.as_view(
        template_name='posts/user_info.html'),
        name='user'),
    url(r'^(?P<slug>[-\w]+)/add_comment/$', add_comment,
        name='add_comment'),
    url(r'^(?P<slug>[-\w]+)/$', PostDetailView.as_view(),
        name='post_detail'),
]

models.py
#encoding: UTF-8
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from unidecode import unidecode


class UserExtend(models.Model):
    user = models.OneToOneField(User, verbose_name=u'Логин')
    town = models.CharField(u'Город', max_length=100, blank=True)
    age = models.IntegerField(u'Возраст', blank=True)
    organization = models.CharField(u'Организация', max_length=100, blank=True)
    tel = models.CharField(u'Телефон', max_length=15, blank=True)

    def __unicode__(self):
        return unicode(self.user)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_absolute_url(self):
        return "/posts/authors/%i/" % self.id


class Post(models.Model):
    title = models.CharField(u'Заголовок', max_length=300)
    slug = models.SlugField(u"URL", default='')
    created = models.DateTimeField(u'Дата публикации', auto_now_add=True)
    modified = models.DateTimeField(u'Дата изменения', auto_now=True)
    author = models.ForeignKey(User, verbose_name=u'Автор', blank=True)
    abstract = models.TextField(u'Краткое содержание (макс. 1000 знаков)', max_length=1000)
    content = RichTextField(u'Текст')
    tags = TaggableManager(help_text="""Вводите теги через запятую.
        Теги могут состоять из нескольких слов. Например: гималайская соль, портал, дровяная печь, канадский кедр.""")
    activity = models.BooleanField(u"Активность", default=False)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-modified']


class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='comment_created')
    author = models.ForeignKey(User, blank=True, null=True)
    content = models.TextField(max_length=1000)
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.content[:60]))

    class Meta:
        ordering = ['-created']

templates/posts/post_base.html
{% extends 'base.html' %}


{% block content %}
  <div class="wrapper">
      <div class="row row-top">
          <div class="col-sm-6">
              {% block post_header %}{% endblock %}
          </div>
          <div class="col-sm-6">
              <div class="pull-right">
                  {% if user.is_authenticated %}
                      {% block user_label %}
                        <span class="label label-default label-user">{{ user.username }}</span>
                      {% endblock %}
                      <a class="btn btn-default" href="{% url 'auth_logout' %}" role="button">Выйти</a>
                  {% else %}
                      <a class="btn btn-default" href="{% url 'auth_login' %}" role="button">Войти</a>
                      <a class="btn btn-primary btn-reg" href="{% url 'registration_register' %}" role="button">Регистрация</a>
                  {% endif %}
              </div>
          </div>
      </div>
      {% if user.is_authenticated %}
      <div class="col-md-3 col-sm-3">
          <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="140">
              <li><a href="{% url 'posts' %}"><i class="fa fa-list-alt"></i> Все обсуждения</a></li>
              <li><a href="{% url 'post_new' %}"><i class="fa fa-pencil"></i> Новое обсуждение</a></li>
              <li><a href="{% url 'my_posts' %}"><i class="fa fa-list-alt"></i> Мои обсуждения</a></li>
              <li><a href="{% url 'my_comments' %}"><i class="fa fa-comments"></i> Мои комментарии</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> Мои сообщения</a></li>
              <li><a href="{% url 'profile' %}"><i class="fa fa-cog"></i> Профиль</a></li>
          </ul>
      </div>
      {% else %}
      <div class="col-md-3 col-sm-3">
          <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="140">
              <li><a href="{% url 'posts' %}"><i class="fa fa-list-alt"></i> Все обсуждения</a></li>
              <li><a href="#"><i class="fa fa-users"></i> Все пользователи</a></li>
          </ul>
      </div>
      {% endif %}
      <div class="col-md-9 col-sm-9 posts-main">
          {% block post_content %}{% endblock %}
       </div>
  </div>

{% endblock %}

{% block contacts %}{% endblock %}

templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}


{% block title %}Обсуждения {{ block.super }}{% endblock %}

{% block post_header %}<h1 class="no-border-header">Обсуждения</h1>{% endblock %}

{% block post_content %}

    <form action="" method="post">{% csrf_token %}
        <div class="alert alert-warning" role="alert">
            <p><i class="fa fa-exclamation-triangle"></i> Вы уверены что хотите удалить обсуждение "{{ object }}"?</p>
        </div>
        <input class="btn btn-primary" type="submit" value="Удалить" />
    </form>

{% endblock %}

templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% load crispy_forms_tags %}


{% block title %} {{ post.title }} - Обсуждения {{ block.super }}{% endblock %}
{% block post_header %}<h2 class="posts-h1 no-border-header">Страница обсуждения</h2>{% endblock %}

{% block post_content %}
<p class="sm-link"><a href="{% url 'posts' %}"><i class="fa fa-angle-left"></i> Назад ко всем обсуждениям</a></p>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            {{ post.title }}
            {% if not post.activity %}
                <strong>(На модерации)</strong>
            {% endif %}
            {% if post.author == user %}
                <a href="{% url 'post_delete' post.slug %}" class="pull-right post-delete-icon" title="Удалить">
                    <i class="fa fa-times"></i>
                </a>
                <a href="{% url 'post_update' post.slug %}" class="pull-right post-update-icon" title="Редактировать">
                    <i class="fa fa-pencil"></i>
                </a>
            {% endif %}
        </h3>
    </div>
    <div class="panel-body">
        <p class="post-date"><i class="fa fa-clock-o"></i> {{ post.created }}</p>
            {{ post.content|safe }}
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-4">
                <p class="post-user">
                    <i class="fa fa-user"></i>
                    <a href="{% url 'user' post.author.id %}">
                        {{ post.author }}
                    </a>
                </p>
            </div>
            <div class="col-sm-8">
                <p class="post-tags">
                    {% if post.tags.all|length %}
                        <i class="fa fa-tags"></i>
                        {% for tag in post.tags.all %}
                            {% if forloop.last %}
                                <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>
                            {% else %}
                                <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>,
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
    <p id="comments">Комментарии ({{ comments|length }}):</p>

<div class="col-md-8">
    {% for comment in comments %}
        <div class="comment">
            <p class="post-date">
                {{ comment.created }} | <a href="{% url 'user' comment.author.id %}">{{ comment.author }} </a>
            </p>
            <div class="content">{{ comment.content }}</div>
        </div>
    {% empty %}
        <p>Здесь еще нет комментариев. Оставьте первым!</p>
    {% endfor %}

    {% if post.activity %}
        {% if user.is_authenticated %}
            <div class="comment-add">
                <form action="{% url 'add_comment' post.slug %}" method="POST">{% csrf_token %}
                    <div id="comment-form">
                        {{ form|crispy }}
                    </div>
                    <div id="submit"><input type="submit" class="btn btn-default" value="Добавить"></div>
                </form>
            </div>
        {% else %}
            <p>Для того, чтобы оставить свой комментарий, Вам необходимо
                <a href="{% url 'auth_login' %}">Войти</a>.
            </p>
            <p class="sm-link">
                <a href="{% url 'posts' %}"><i class="fa fa-angle-left"></i> Назад ко всем обсуждениям</a>
            </p>
        {% endif %}
    {% else %}
        <p>Комментарии отключены, т.к. пост находится на модерации</p>
    {% endif %}
</div>


{% endblock %}

templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load crispy_forms_tags %}


{% block title %}Создание нового поста {{ block.super }}{% endblock %}
{% block post_header %}<h1 class="no-border-header">Создание нового обсуждения</h1>{% endblock %}

{% block post_content %}
<p class="sm-link"><a href="{% url 'posts' %}"><i class="fa fa-angle-left"></i> Назад ко всем обсуждениям</a></p>
<div class="panel panel-default">
    <div class="panel-body">
        <form method="post" action=".">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Опубликовать</button>
        </form>
    </div>
</div>

<p class="sm-link"><a href="{% url 'posts' %}"><i class="fa fa-angle-left"></i> Назад ко всем обсуждениям</a></p>

{% endblock %}

templates/posts/post_list.html
{% extends 'posts/post_base.html' %}


{% block title %}Обсуждения {{ block.super }}{% endblock %}

{% block post_header %}<h1 class="no-border-header">Обсуждения</h1>{% endblock %}

{% block post_content %}

{% for post in posts %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                {% if post.author == user %}
                    <a href="{% url 'post_delete' post.slug %}" class="pull-right post-delete-icon" title="Удалить">
                        <i class="fa fa-times"></i>
                    </a>
                    <a href="{% url 'post_update' post.slug %}" class="pull-right post-update-icon" title="Редактировать">
                        <i class="fa fa-pencil"></i>
                    </a>
                {% endif %}
            </h3>
        </div>
        <div class="panel-body">
            <p class="post-date"><i class="fa fa-clock-o"></i> {{ post.created }}</p>
            {{ post.abstract }}
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-3">
                    <p class="post-user">
                        <a href="{% url 'user' post.author.id %}"><i class="fa fa-user"></i> {{ post.author }}</a>
                    </p>
                </div>
                <div class="col-sm-2">
                    <p class="post-comments">
                        <a href="{{ post.get_absolute_url }}#comments"><i class="fa fa-comment"></i>
                            {{ post.comment_set.all|length }}</a>
                    </p>
                </div>
                {% if is_profile %}
                    <div class="col-sm-3">
                        {% if post.activity %}
                            <p class="post-status">Активен</p>
                        {% else %}
                            <p class="post-status">На модерации</p>
                        {% endif %}
                    </div>
                    <div class="col-sm-4">
                {% else %}
                    <div class="col-sm-7">
                {% endif %}
                    <p class="post-tags">
                        {% if post.tags.all|length %}
                            <i class="fa fa-tags"></i>
                            {% for tag in post.tags.all %}
                                {% if forloop.last %}
                                    <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>
                                {% else %}
                                    <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>,
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <p>Здесь еще нет постов.</p>
{% endfor %}

{% if is_paginated %}
    <nav>
         <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="/posts?page={{ page_obj.previous_page_number }}">Назад</a></li>
            {% endif %}
            <span class="page-current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <li><a href="/posts?page={{ page_obj.next_page_number }}">Вперед</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{% endblock %}

templates/posts/profile.html
{% extends 'posts/post_base.html' %}


{% block title %} {{ user.username }} {{ block.super }}{% endblock %}
{% block post_header %}<h1 class="no-border-header">Профиль пользователя</h1>{% endblock %}
{% block user_label %}<span class="label label-default label-user">{{ user.username }}</span>{% endblock %}


{% block post_content %}

<h3>{{ user.username }}
{#        <span class="sm-link pull-right">#}
{#            <a href="{% url 'profile_update' %}"><i class="fa fa-pencil"></i> редактировать профиль</a>#}
{#        </span>#}
</h3>
<table class="table table-hover">
    <thead></thead>
    <tbody>

        {% if user.author.first_name or user.author.first_name %}
            <tr>
                <td>ФИО: </td>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>На сайте saunaflame с: </td>
            <td>{{ user.date_joined | date:'d E Y' }} г. </td>
        </tr>
        <tr>
            <td>Заходил на сайт: </td>
            <td>{{ user.last_login | date:'d E Y' }} г. в {{ user.last_login | time:'H:i'}}</td>
        </tr>
        <tr>
            <td>Обсуждений: </td>
            <td>{{ posts.all|length }}</td>
        </tr>
        <tr>
            <td>Комментариев: </td>
            <td>{{ user.comment_set.all|length }}</td>
        </tr>
        {% if user.author.town %}
            <tr>
                <td>Город: </td>
                <td>{{ user.author.town }}</td>
            </tr>
        {% endif %}
        {% if user.author.age %}
            <tr>
                <td>Возраст: </td>
                <td>{{ user.author.age }}</td>
            </tr>
        {% endif %}
        {% if user.author.organization %}
            <tr>
                <td>Организация: </td>
                <td>{{ user.author.organization }}</td>
            </tr>
        {% endif %}
    </tbody>
</table>

    <h4 class="h4-posts">Последние обсуждения</h4>
    {% if posts|length != 0 %}
        <ul class="ul-posts">
            {% for post in posts|slice:'3' %}
                <li><a href="{% url 'post_detail' post.slug %}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>У <strong>{{ user.username }}</strong> еще нет обсуждений</p>
    {% endif %}

    <h4 class="h4-posts">Последние комментарии</h4>
    <div class="col-md-8">
        {% for comment in user.comment_set.all|slice:'3' %}
            <div class="comment">
                <div class="content">{{ comment.content }}</div>
                <p class="link-to-post">в обсуждении <a href="{% url 'post_detail' comment.post.slug %}">{{ comment.post.title }}</a></p>
            </div>
        {% empty %}
            <p><strong>{{ user.username }}</strong> еще не оставлял комментарии</p>
        {% endfor %}
    </div>

{% endblock %}

templates/posts/user_comment_list.html
{% extends 'posts/post_base.html' %}


{% block title %}
    {% if current_user %}
        Комментарии пользователя {{ current_user }}
    {% else %}
        Комментарии
    {% endif %}
    {{ block.super }}
{% endblock %}

{% block post_header %}<h1 class="no-border-header">
    {% if current_user %}
        Мои комментарии
    {% else %}
        Комментарии
    {% endif %}</h1>
{% endblock %}

{% block post_content %}
<h4>Всего комментариев: {{ comments|length }}</h4>

<div class="col-md-8">
    {% for comment in comments %}
        <div class="comment">
            <div class="content">{{ comment.content }}</div>
            <p class="link-to-post">в обсуждении <a href="{% url 'post_detail' comment.post.slug %}">{{ comment.post.title }}</a></p>
        </div>
    {% empty %}
        <p>Здесь еще нет комментариев.</p>
    {% endfor %}
</div>

{% if is_paginated %}
    <nav>
         <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="/posts?page={{ page_obj.previous_page_number }}">Назад</a></li>
            {% endif %}
            <span class="page-current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <li><a href="/posts?page={{ page_obj.next_page_number }}">Вперед</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{% endblock %}

templates/posts/user_form.html
{% extends 'posts/post_base.html' %}
{% load crispy_forms_tags %}


{% block title %}{{ user.username }} - редактирование профиля {{ block.super }}{% endblock %}
{% block post_header %}<h1 class="no-border-header">Профиль пользователя</h1>{% endblock %}

{% block post_content %}

<div class="col-md-8 col-md-offset-1">
    <p class="sm-link"><a href="{% url 'profile' %}"><i class="fa fa-angle-left"></i> Отменить редактирование</a></p>
    <form method="post" action=".">
        {% for userform in userforms %}
            {{ userform }}
        {% endfor %}
        {% for post_formset in post_formsets %}
            {{ post_formset }}
        {% endfor %}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
    <p class="sm-link"><a href="{% url 'profile' %}"><i class="fa fa-angle-left"></i> Отменить редактирование</a></p>
</div>

{% endblock %}

templates/posts/user_info.html
{% extends 'posts/post_base.html' %}


{% block title %} {{ current_user.username }} {{ block.super }}{% endblock %}
{% block post_header %}<h1 class="no-border-header">Профиль пользователя</h1>{% endblock %}
{% block user_label %}<span class="label label-default">{{ user.username }}</span>{% endblock %}


{% block post_content %}

<h3>{{ current_user.username }}
{#    {% if is_profile == True %}#}
{#        <span class="sm-link pull-right">#}
{#            <a href="{% url 'profile_update' %}"><i class="fa fa-pencil"></i> редактировать профиль</a>#}
{#        </span>#}
{#    {% endif %}#}
</h3>
<table class="table table-hover">
    <thead></thead>
    <tbody>

        {% if current_user.author.first_name or current_user.author.first_name %}
            <tr>
                <td>ФИО: </td>
                <td>{{ current_user.first_name }} {{ current_user.last_name }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>На сайте saunaflame с: </td>
            <td>{{ current_user.date_joined | date:'d E Y' }} г. </td>
        </tr>
        <tr>
            <td>Заходил на сайт: </td>
            <td>{{ current_user.last_login | date:'d E Y' }} г. в {{ current_user.last_login | time:'H:i'}}</td>
        </tr>
        <tr>
            <td>Обсуждений: </td>
            <td>{{ current_user.post_set.all|length }}</td>
        </tr>
        <tr>
            <td>Комментариев: </td>
            <td>{{ current_user.comment_set.all|length }}</td>
        </tr>
        {% if current_user.author.town %}
            <tr>
                <td>Город: </td>
                <td>{{ current_user.author.town }}</td>
            </tr>
        {% endif %}
        {% if current_user.author.age %}
            <tr>
                <td>Возраст: </td>
                <td>{{ current_user.author.age }}</td>
            </tr>
        {% endif %}
        {% if current_user.author.organization %}
            <tr>
                <td>Организация: </td>
                <td>{{ current_user.author.organization }}</td>
            </tr>
        {% endif %}
    </tbody>
</table>

    <h4 class="h4-posts">Последние обсуждения</h4>
    {% if current_user.post_set.all|length != 0 %}
        <ul class="ul-posts">
            {% for post in current_user.post_set.all|slice:'3' %}
                <li><a href="{% url 'post_detail' post.slug %}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>У <strong>{{ current_user.username }}</strong> еще нет обсуждений</p>
    {% endif %}

    <h4 class="h4-posts">Последние комментарии</h4>

    <div class="col-md-8">
        {% for comment in current_user.comment_set.all|slice:'3' %}
            <div class="comment">
                <div class="content">{{ comment.content }}</div>
                <p class="link-to-post">в обсуждении <a href="{% url 'post_detail' comment.post.slug %}">
                    {{ comment.post.title }}</a>
                </p>
            </div>
        {% empty %}
            <p><strong>{{ current_user.username }}</strong> еще не оставлял комментарии</p>
        {% endfor %}
    </div>

{% endblock %}

templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}


{% block title %} Обсуждения пользователя {{ user }} {{ block.super }}{% endblock %}

{% block post_header %}<h1 class="no-border-header">Мои обсуждения</h1>{% endblock %}

{% block post_content %}
    <h4>Всего обсуждений: {{ posts|length }}</h4>

    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    <a href="{% url 'post_delete' post.slug %}" class="pull-right post-delete-icon" title="Удалить">
                        <i class="fa fa-times"></i>
                    </a>
                    <a href="{% url 'post_update' post.slug %}" class="pull-right post-update-icon" title="Редактировать">
                        <i class="fa fa-pencil"></i>
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                <p class="post-date"><i class="fa fa-clock-o"></i> {{ post.created }}</p>
                {{ post.content|safe }}
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-3">
                        <p class="post-user">
                            <a href="{% url 'user' post.author.id %}"><i class="fa fa-user"></i> {{ post.author }}</a>
                        </p>
                    </div>
                    <div class="col-sm-2">
                        <p class="post-comments">
                            <a href="{{ post.get_absolute_url }}#comments"><i class="fa fa-comment"></i>
                            {{ post.comment_set.all|length }}</a>
                        </p>
                    </div>
                    <div class="col-sm-3">
                        {% if is_profile %}
                            {% if post.activity %}
                                <p class="post-status">Активен</p>
                            {% else %}
                                <p class="post-status">На модерации</p>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-sm-4">
                        <p class="post-tags">
                            {% if post.tags.all|length %}
                                <i class="fa fa-tags"></i>
                                {% for tag in post.tags.all %}
                                    {% if forloop.last %}
                                        <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>
                                    {% else %}
                                        <a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>,
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <p>Здесь еще нет обсуждений.</p>
    {% endfor %}

    {% if is_paginated %}
        <nav>
             <ul class="pager">
                {% if page_obj.has_previous %}
                    <li><a href="/posts?page={{ page_obj.previous_page_number }}">Назад</a></li>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <li><a href="/posts?page={{ page_obj.next_page_number }}">Вперед</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}